# Pivot Table
The pivot table takes simple column-wise data as input, and groups the entries into a two-dimenssional table that provides a multidimenssional summarization of the data.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.groupby('sex')[['total_bill']].mean()

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\2388094044.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [5]:
df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\884363850.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [8]:
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='std')

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\2838718441.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='std')

smoker       Yes        No
sex
Male    9.911845  8.726566
Female  9.189751  7.286455

In [11]:
df.pivot_table(
    index='sex',
    columns='smoker',
    values=df.select_dtypes(include='number').columns
)

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\1395176754.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(

            size                 tip           total_bill
smoker       Yes        No       Yes        No        Yes         No
sex
Male    2.500000  2.711340  3.051167  3.113402  22.284500  19.791237
Female  2.242424  2.592593  2.931515  2.773519  17.977879  18.105185

In [13]:
# multidimessional
df.pivot_table(index=['sex','smoker'],columns=['day','time'],aggfunc={'size':'mean','tip':'max','total_bill':'sum'},margins=True)

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\2377919304.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=['sex','smoker'],columns=['day','time'],aggfunc={'size':'mean','tip':'max','total_bill':'sum'},margins=True)

                   size                                                 \
day                Thur              Fri                 Sat       Sun
time              Lunch Dinner     Lunch    Dinner    Dinner    Dinner
sex    smoker
Male   Yes     2.300000    NaN  1.666667  2.400000  2.629630  2.600000
       No      2.500000    NaN       NaN  2.000000  2.656250  2.883721
Female Yes     2.428571    NaN  2.000000  2.000000  2.200000  2.500000
       No      2.500000    2.0  3.000000  2.000000  2.307692  3.071429
All            2.459016    2.0  2.000000  2.166667  2.517241  2.842105

                          tip               ...       total_bill         \
day                 All  Thur          Fri  ...   All       Thur
time                    Lunch Dinner Lunch  ...            Lunch Dinner
sex    smoker                               ...
Male   Yes     2.500000  5.00    NaN  2.20  ...  10.0     191.71   0.00
       No      2.711340  6.70    NaN   NaN  ...   9.0     369.73   0.00
Female Yes     2.242424  5.00    NaN  3.48  ...   6.5     134.53   0.00
       No      2.592593  5.17    3.0  3.00  ...   5.2     381.58  18.78
All            2.569672  6.70    3.0  3.48  ...  10.0    1077.55  18.78


day              Fri           Sat            Sun               All
time           Lunch  Dinner Lunch   Dinner Lunch   Dinner
sex    smoker
Male   Yes     34.16  129.46   0.0   589.62   0.0   392.12  1337.07
       No       0.00   34.95   0.0   637.73   0.0   877.34  1919.75
Female Yes     39.78   48.80   0.0   304.00   0.0    66.16   593.27
       No      15.98   22.75   0.0   247.05   0.0   291.54   977.68
All            89.92  235.96   NaN  1778.40   NaN  1627.16  4827.77

[5 rows x 23 columns]

In [14]:
# margins
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum',margins=True)

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\1561592577.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum',margins=True)

smoker      Yes       No      All
sex
Male    1337.07  1919.75  3256.82
Female   593.27   977.68  1570.95
All     1930.34  2897.43  4827.77