# Pivot Table
The pivot table takes simple column-wise data as input, and groups the entries into a two-dimenssional table that provides a multidimenssional summarization of the data.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.groupby('sex')[['total_bill']].mean()

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\2388094044.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [5]:
df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\884363850.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [8]:
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='std')

C:\Users\rabiu\AppData\Local\Temp\ipykernel_19752\2838718441.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='std')

smoker       Yes        No
sex
Male    9.911845  8.726566
Female  9.189751  7.286455